packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependenciesMeta:
      typescript:
        optional: false
  "@graphql-codegen/cli@*":
    dependencies:
      typescript: "*"
  eslint-plugin-graphql@*:
    peerDependenciesMeta:
      typescript:
        optional: false
  babel-plugin-styled-components@*:
    dependencies:
      react: "*"
      react-dom: "*"
      react-is: "*"
      styled-components: "*"
  gatsby-plugin-material-ui@*:
    dependencies:
      core-js: "*"
    peerDependenciesMeta:
      "@babel/core":
        optional: false
  gatsby-plugin-mdx@*:
    dependencies:
      eslint: "*"
      babel-eslint: "*"
      gatsby: "*"
      gatsby-plugin-sharp: "*"
      gatsby-remark-autolink-headers: "*"
      gatsby-remark-embed-video: "*"
      gatsby-remark-images: "*"
  gatsby@*:
    dependencies:
      babel-eslint: "*"
      babel-plugin-styled-components: "*"
      typescript: "*"
  react-dev-utils@*:
    peerDependenciesMeta:
      typescript:
        optional: false
      webpack:
        optional: false
  react-live@*:
    peerDependenciesMeta:
      react:
        optional: false
      react-dom:
        optional: false
  styled-components@*:
    dependencies:
      react-is: "*"
  graphql-config@*:
    peerDependenciesMeta:
      typescript:
        optional: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-sources.cjs
