plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-sources.cjs

packageExtensions:
  # awaiting fix: https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/issues/147
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "gatsby-plugin-material-ui@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      "core-js":
        optional: true
  "gatsby@*":
    peerDependenciesMeta:
      "babel-eslint":
        optional: true
  "react-dev-utils@*":
    peerDependenciesMeta:
      "typescript":
        optional: true
      "webpack":
        optional: true
  "react-live@*":
    peerDependenciesMeta:
      "react":
        optional: true
      "react-dom":
        optional: true
