nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependenciesMeta:
      typescript:
        optional: false
  babel-plugin-styled-components@*:
    dependencies:
      styled-components: "*"
  eslint-plugin-graphql@*:
    peerDependenciesMeta:
      typescript:
        optional: false
  gatsby-plugin-mdx@*:
    dependencies:
      babel-eslint: "*"
      eslint: "*"
      gatsby-remark-autolink-headers: "*"
    peerDependenciesMeta:
      gatsby:
        optional: false
      gatsby-plugin-sharp:
        optional: false
      gatsby-remark-images:
        optional: false
  gatsby@*:
    dependencies:
      babel-eslint: "*"
      typescript: "*"
  glyphhanger@*:
    dependencies:
      puppeteer: "*"
  graphql-config@*:
    peerDependenciesMeta:
      typescript:
        optional: false
  vercel@*:
    dependencies:
      esprima: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
