nodeLinker: node-modules

packageExtensions:
  babel-plugin-styled-components@*:
    dependencies:
      styled-components: "*"
  gatsby-plugin-mdx@*:
    dependencies:
      babel-eslint: "*"
      eslint: "*"
      gatsby-remark-autolink-headers: "*"
    peerDependenciesMeta:
      gatsby:
        optional: false
      gatsby-plugin-sharp:
        optional: false
      gatsby-remark-images:
        optional: false
  gatsby@*:
    dependencies:
      babel-eslint: "*"
      typescript: "*"
  glyphhanger@*:
    dependencies:
      puppeteer: "*"
  vercel@*:
    dependencies:
      esprima: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
