compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@gatsbyjs/parcel-namer-relative-to-cwd@*":
    peerDependencies:
      "@parcel/core": "*"
  "@graphql-tools/graphql-tag-pluck@*":
    dependencies:
      "@babel/core": "*"
  "@parcel/bundler-default@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/compressor-raw@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/namer-default@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-terser@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-js@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-raw@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/plugin@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/reporter-dev-server@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/resolver-default@*":
    peerDependencies:
      "@parcel/core": "*"
      assert: "*"
      browserify-zlib: "*"
      buffer: "*"
      console-browserify: "*"
      constants-browserify: "*"
      crypto-browserify: "*"
      domain-browser: "*"
      events: "*"
      https-browserify: "*"
      os-browserify: "*"
      path-browserify: "*"
      process: "*"
      punycode: "*"
      querystring-es3: "*"
      stream-browserify: "*"
      stream-http: "*"
      string_decoder: "*"
      timers-browserify: "*"
      tty-browserify: "*"
      url: "*"
      util: "*"
      vm-browserify: "*"
  "@parcel/runtime-js@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-json@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/types@*":
    peerDependencies:
      "@parcel/core": "*"
  gatsby-parcel-config@*:
    peerDependencies:
      assert: "*"
      browserify-zlib: "*"
      buffer: "*"
      console-browserify: "*"
      constants-browserify: "*"
      crypto-browserify: "*"
      domain-browser: "*"
      events: "*"
      https-browserify: "*"
      os-browserify: "*"
      path-browserify: "*"
      process: "*"
      punycode: "*"
      querystring-es3: "*"
      stream-browserify: "*"
      stream-http: "*"
      string_decoder: "*"
      timers-browserify: "*"
      tty-browserify: "*"
      url: "*"
      util: "*"
      vm-browserify: "*"
  gatsby-plugin-feed@*:
    peerDependencies:
      graphql: "*"
  gatsby@*:
    peerDependencies:
      assert: "*"
      babel-eslint: "*"
      browserify-zlib: "*"
      buffer: "*"
      console-browserify: "*"
      constants-browserify: "*"
      crypto-browserify: "*"
      domain-browser: "*"
      events: "*"
      https-browserify: "*"
      os-browserify: "*"
      path-browserify: "*"
      process: "*"
      punycode: "*"
      querystring-es3: "*"
      stream-browserify: "*"
      stream-http: "*"
      string_decoder: "*"
      timers-browserify: "*"
      tty-browserify: "*"
      typescript: "*"
      url: "*"
      util: "*"
      vm-browserify: "*"

yarnPath: .yarn/releases/yarn-4.5.1.cjs
