import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";
import {
  ALL_POST_PATHS,
  POSTS_PATH,
} from "packages/nextjs-site/utils/mdx-utils";
import path from "path";

type Post = {
  content: string;
  data: {
    [key: string]: any;
  };
  filePath: string;
};

export default function Index({ posts }: { posts: Post[] }) {
  return (
    <>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`/blog/${post.filePath.replace(/\.mdx?$/, "")}`}
              href={`/blog/[slug]`}
            >
              <a>{post.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </>
  );
}

export function getStaticProps() {
  const posts = ALL_POST_PATHS.map((filePath) => {
    const sourceFile = path.join(POSTS_PATH, filePath);
    const { content, data } = matter.read(sourceFile);

    return {
      content,
      data,
      filePath,
    };
  });

  return { props: { posts } };
}
