version: 2.1

workflows:
  version: 2.1
    build_and_deploy:
      jobs:
        - build
        - deploy:
            filters:
              branches:
                only:
                  - production

executors:
  docker_executor:
    docker:
      - image: circleci/node:13.7.0
    working_directory: ~/repo

commands:
  checkout_with_cache:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    executor: docker_executor
    steps:
      - checkout_with_cache
      - run: npm run build
  deploy:
    executor: docker_executor
    steps:
      - checkout_with_cache
      - run: npm run deploy
