version: 2.1

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - deploy

  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - develop

executors:
  docker_executor:
    docker:
      - image: circleci/node:14.2.0
    working_directory: ~/repo

commands:
  checkout_with_cache:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    executor: docker_executor
    steps:
      - checkout_with_cache
      - run: yarn build
  deploy:
    executor: docker_executor
    steps:
      - checkout_with_cache
      - run: yarn build
      - run: yarn deploy
